# Generated by Django 4.2.5 on 2023-09-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_post_updated_at_post_updated_by_topic_topic_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
